version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=bale.redis.ir!
    command: redis-server --requirepass ${REDIS_PASSWORD}

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: bale
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: bale.postgres.ir!


    ports:
      - 5432:5432
    volumes:
      - ../../../data/postgres:/var/lib/postgresql/data
    restart: always